server:
  port: ${server.port}
  servlet:
  context-path: ${server.context-path}
mybatis:
  type-aliases-package: com.melt.spring.boot.helloword.entity
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: cloud-provider
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10


